/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        navy: {
          DEFAULT: '#0F172A',
          50: '#F0F4FA',
          100: '#D5E1F2',
          200: '#AAC3E5',
          300: '#7FA5D8',
          400: '#5487CB',
          500: '#2A69BE',
          600: '#1E3A5F',
          700: '#172554',
          800: '#0F172A',
          900: '#080D15',
        },
        brand: {
          indigo: '#2563EB',
          'indigo-light': '#DBEAFE',
          emerald: '#10B981',
          'emerald-light': '#D1FAE5',
          purple: '#8B5CF6',
          'purple-light': '#EDE9FE',
          orange: '#F97316',
          'orange-light': '#FFF7ED',
          slate: '#64748B',
          red: '#EF4444',
          'red-light': '#FEE2E2',
        },
      },
      borderRadius: { lg: "14px", md: "10px", sm: "8px" },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.02)',
        'card-hover': '0 8px 25px rgba(0,0,0,0.08), 0 2px 8px rgba(0,0,0,0.04)',
        sidebar: '1px 0 0 0 rgba(255,255,255,0.06)',
        topbar: '0 1px 0 rgba(0,0,0,0.04)',
        'kpi': '0 1px 3px rgba(0,0,0,0.03)',
        'kpi-hover': '0 8px 30px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
}
